export const FETCH_ASSETS_FULFILLED = 'FETCH_ASSETS_FULFILLED';
export const SET_ROUTER = 'SET_ROUTER';
export const SET_CURRENT = 'SET_CURRENT';
export const SET_CURRENT_TYPE = 'SET_CURRENT_TYPE';
export const SET_CURRENT_COLOR = 'SET_CURRENT_COLOR';
export const SET_ASSET_INDEX = 'SET_ASSET_INDEX';
