export const FETCH_ASSETS = 'FETCH_ASSETS';
export const FETCH_ASSETS_FULFILLED = 'FETCH_ASSETS_FULFILLED';
export const SET_CURRENT_ASSET = 'SET_CURRENT_ASSET';
export const INCREMENT_ASSET = 'INCREMENT_ASSET';
export const DECREMENT_ASSET = 'DECREMENT_ASSET';
