export const FETCH_ASSETS = 'FETCH_ASSETS';
export const FETCH_ASSETS_FULFILLED = 'FETCH_ASSETS_FULFILLED';
export const SET_CURRENT_ASSET = 'SET_CURRENT_ASSET';
export const SET_ASSET_INDEX = 'SET_ASSET_INDEX';
export const SET_CURRENT_COLOR = 'SET_CURRENT_COLOR';