export const SHOW_FORM = 'SHOW_FORM';
export const SET_EMAIL = 'SET_EMAIL';
export const SUBMIT_FORM = 'SUBMIT_FORM';
export const CHECK_PAYMENT = 'CHECK_PAYMENT';
export const CHECK_PAYMENT_FULFILLED = 'CHECK_PAYMENT_FULFILLED';
