export const UPDATE_PROFILE_ASSET = 'UPDATE_PROFILE_ASSET';
export const UPDATE_PROFILE_ASSET_TYPE = 'UPDATE_PROFILE_ASSET_TYPE';
export const UPDATE_PROFILE_ASSET_COLOR = 'UPDATE_PROFILE_ASSET_COLOR';
export const UPDATE_PROFILE_ASSET_VISIBILITY = 'UPDATE_PROFILE_ASSET_VISIBILITY';
export const CHANGE_PROFILE_ASSET_TYPE_STYLE = 'CHANGE_PROFILE_ASSET_TYPE_STYLE';
export const CHANGE_PROFILE_ASSET_SORT_ORDER = 'CHANGE_PROFILE_ASSET_SORT_ORDER';
