export const UPDATE_PROFILE_ASSET = 'UPDATE_PROFILE_ASSET';
export const UPDATE_PROFILE_ASSET_TYPE = 'UPDATE_PROFILE_ASSET_TYPE';
export const UPDATE_PROFILE_ASSET_COLOR = 'UPDATE_PROFILE_ASSET_COLOR';
export const UPDATE_PROFILE_ASSET_VISIBILITY = 'UPDATE_PROFILE_ASSET_VISIBILITY';
export const MOVE_PROFILE_ASSET_TYPE = 'MOVE_PROFILE_ASSET_TYPE';
